apiVersion: v1
kind: Service
metadata:
  name: block-xplorer-service
  namespace: block-xplorer
spec:
  selector:
    app: block-xplorer
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
  type: NodePort
