apiVersion: v1
kind: Service
metadata:
  name: block-xplorer-service
  namespace: block-xplorer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  selector:
    app: block-xplorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
