apiVersion: v1
kind: Service
metadata:
  name: block-xplorer-service
  namespace: block-xplorer
  selector:
    app: block-xplorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
