apiVersion: apps/v1
kind: Deployment
metadata:
  name: block-xplorer-deployment
  namespace: block-xplorer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: block-xplorer
  template:
    metadata:
      labels:
        app: block-xplorer
    spec:
      containers:
      - name: block-xplorer
        image: 941377111777.dkr.ecr.us-east-2.amazonaws.com/block-xplorer:latest
        env:
        - name: INFURA_API_KEY
          valueFrom:
            secretKeyRef:
              name: infura-api-key
              key: INFURA_API_KEY
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "100m"    # 100 milliCPU
            memory: "128Mi" # 128 MiB of memory
          limits:
            cpu: "500m"    # 500 milliCPU
            memory: "512Mi" # 512 MiB of memory
